/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QaRouteImport } from './routes/qa'
import { Route as PremiumSuccessRouteImport } from './routes/premium-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropDoctorRouteImport } from './routes/crop-doctor'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiPayfastNotifyRouteImport } from './routes/api/payfast/notify'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSuccessRoute = PremiumSuccessRouteImport.update({
  id: '/premium-success',
  path: '/premium-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDoctorRoute = CropDoctorRouteImport.update({
  id: '/crop-doctor',
  path: '/crop-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPayfastNotifyRoute = ApiPayfastNotifyRouteImport.update({
  id: '/api/payfast/notify',
  path: '/api/payfast/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/qa': typeof QaRoute
  '/register': typeof RegisterRoute
  '/tips': typeof TipsRoute
  '/upgrade': typeof UpgradeRoute
  '/weather': typeof WeatherRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/qa': typeof QaRoute
  '/register': typeof RegisterRoute
  '/tips': typeof TipsRoute
  '/upgrade': typeof UpgradeRoute
  '/weather': typeof WeatherRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/qa': typeof QaRoute
  '/register': typeof RegisterRoute
  '/tips': typeof TipsRoute
  '/upgrade': typeof UpgradeRoute
  '/weather': typeof WeatherRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/crop-doctor'
    | '/dashboard'
    | '/login'
    | '/premium-success'
    | '/qa'
    | '/register'
    | '/tips'
    | '/upgrade'
    | '/weather'
    | '/profile'
    | '/tasks'
    | '/api/payfast/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/crop-doctor'
    | '/dashboard'
    | '/login'
    | '/premium-success'
    | '/qa'
    | '/register'
    | '/tips'
    | '/upgrade'
    | '/weather'
    | '/profile'
    | '/tasks'
    | '/api/payfast/notify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/calculator'
    | '/crop-doctor'
    | '/dashboard'
    | '/login'
    | '/premium-success'
    | '/qa'
    | '/register'
    | '/tips'
    | '/upgrade'
    | '/weather'
    | '/_authenticated/profile'
    | '/_authenticated/tasks'
    | '/api/payfast/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CropDoctorRoute: typeof CropDoctorRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PremiumSuccessRoute: typeof PremiumSuccessRoute
  QaRoute: typeof QaRoute
  RegisterRoute: typeof RegisterRoute
  TipsRoute: typeof TipsRoute
  UpgradeRoute: typeof UpgradeRoute
  WeatherRoute: typeof WeatherRoute
  ApiPayfastNotifyRoute: typeof ApiPayfastNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-success': {
      id: '/premium-success'
      path: '/premium-success'
      fullPath: '/premium-success'
      preLoaderRoute: typeof PremiumSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-doctor': {
      id: '/crop-doctor'
      path: '/crop-doctor'
      fullPath: '/crop-doctor'
      preLoaderRoute: typeof CropDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/payfast/notify': {
      id: '/api/payfast/notify'
      path: '/api/payfast/notify'
      fullPath: '/api/payfast/notify'
      preLoaderRoute: typeof ApiPayfastNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CropDoctorRoute: CropDoctorRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PremiumSuccessRoute: PremiumSuccessRoute,
  QaRoute: QaRoute,
  RegisterRoute: RegisterRoute,
  TipsRoute: TipsRoute,
  UpgradeRoute: UpgradeRoute,
  WeatherRoute: WeatherRoute,
  ApiPayfastNotifyRoute: ApiPayfastNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
