/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QaRouteImport } from './routes/qa'
import { Route as PremiumSuccessRouteImport } from './routes/premium-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropDoctorRouteImport } from './routes/crop-doctor'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMyFarmRouteImport } from './routes/_authenticated/my-farm'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedIrrigationRouteImport } from './routes/_authenticated/irrigation'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as ApiPayfastNotifyRouteImport } from './routes/api/payfast/notify'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSuccessRoute = PremiumSuccessRouteImport.update({
  id: '/premium-success',
  path: '/premium-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropDoctorRoute = CropDoctorRouteImport.update({
  id: '/crop-doctor',
  path: '/crop-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyFarmRoute = AuthenticatedMyFarmRouteImport.update({
  id: '/my-farm',
  path: '/my-farm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIrrigationRoute = AuthenticatedIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPayfastNotifyRoute = ApiPayfastNotifyRouteImport.update({
  id: '/api/payfast/notify',
  path: '/api/payfast/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/qa': typeof QaRoute
  '/register': typeof RegisterRoute
  '/tips': typeof TipsRoute
  '/upgrade': typeof UpgradeRoute
  '/weather': typeof WeatherRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/irrigation': typeof AuthenticatedIrrigationRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/market': typeof AuthenticatedMarketRoute
  '/my-farm': typeof AuthenticatedMyFarmRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof AuthenticatedServicesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/qa': typeof QaRoute
  '/register': typeof RegisterRoute
  '/tips': typeof TipsRoute
  '/upgrade': typeof UpgradeRoute
  '/weather': typeof WeatherRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/irrigation': typeof AuthenticatedIrrigationRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/market': typeof AuthenticatedMarketRoute
  '/my-farm': typeof AuthenticatedMyFarmRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof AuthenticatedServicesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/crop-doctor': typeof CropDoctorRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/qa': typeof QaRoute
  '/register': typeof RegisterRoute
  '/tips': typeof TipsRoute
  '/upgrade': typeof UpgradeRoute
  '/weather': typeof WeatherRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/irrigation': typeof AuthenticatedIrrigationRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/my-farm': typeof AuthenticatedMyFarmRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/payfast/notify': typeof ApiPayfastNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/crop-doctor'
    | '/dashboard'
    | '/login'
    | '/premium-success'
    | '/qa'
    | '/register'
    | '/tips'
    | '/upgrade'
    | '/weather'
    | '/bookings'
    | '/browse'
    | '/earnings'
    | '/equipment'
    | '/history'
    | '/irrigation'
    | '/jobs'
    | '/journal'
    | '/market'
    | '/my-farm'
    | '/orders'
    | '/profile'
    | '/services'
    | '/stats'
    | '/tasks'
    | '/api/payfast/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/crop-doctor'
    | '/dashboard'
    | '/login'
    | '/premium-success'
    | '/qa'
    | '/register'
    | '/tips'
    | '/upgrade'
    | '/weather'
    | '/bookings'
    | '/browse'
    | '/earnings'
    | '/equipment'
    | '/history'
    | '/irrigation'
    | '/jobs'
    | '/journal'
    | '/market'
    | '/my-farm'
    | '/orders'
    | '/profile'
    | '/services'
    | '/stats'
    | '/tasks'
    | '/api/payfast/notify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/calculator'
    | '/crop-doctor'
    | '/dashboard'
    | '/login'
    | '/premium-success'
    | '/qa'
    | '/register'
    | '/tips'
    | '/upgrade'
    | '/weather'
    | '/_authenticated/bookings'
    | '/_authenticated/browse'
    | '/_authenticated/earnings'
    | '/_authenticated/equipment'
    | '/_authenticated/history'
    | '/_authenticated/irrigation'
    | '/_authenticated/jobs'
    | '/_authenticated/journal'
    | '/_authenticated/market'
    | '/_authenticated/my-farm'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/services'
    | '/_authenticated/stats'
    | '/_authenticated/tasks'
    | '/api/payfast/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CropDoctorRoute: typeof CropDoctorRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PremiumSuccessRoute: typeof PremiumSuccessRoute
  QaRoute: typeof QaRoute
  RegisterRoute: typeof RegisterRoute
  TipsRoute: typeof TipsRoute
  UpgradeRoute: typeof UpgradeRoute
  WeatherRoute: typeof WeatherRoute
  ApiPayfastNotifyRoute: typeof ApiPayfastNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-success': {
      id: '/premium-success'
      path: '/premium-success'
      fullPath: '/premium-success'
      preLoaderRoute: typeof PremiumSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-doctor': {
      id: '/crop-doctor'
      path: '/crop-doctor'
      fullPath: '/crop-doctor'
      preLoaderRoute: typeof CropDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-farm': {
      id: '/_authenticated/my-farm'
      path: '/my-farm'
      fullPath: '/my-farm'
      preLoaderRoute: typeof AuthenticatedMyFarmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/irrigation': {
      id: '/_authenticated/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof AuthenticatedIrrigationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/payfast/notify': {
      id: '/api/payfast/notify'
      path: '/api/payfast/notify'
      fullPath: '/api/payfast/notify'
      preLoaderRoute: typeof ApiPayfastNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedIrrigationRoute: typeof AuthenticatedIrrigationRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedMyFarmRoute: typeof AuthenticatedMyFarmRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIrrigationRoute: AuthenticatedIrrigationRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedMyFarmRoute: AuthenticatedMyFarmRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CropDoctorRoute: CropDoctorRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PremiumSuccessRoute: PremiumSuccessRoute,
  QaRoute: QaRoute,
  RegisterRoute: RegisterRoute,
  TipsRoute: TipsRoute,
  UpgradeRoute: UpgradeRoute,
  WeatherRoute: WeatherRoute,
  ApiPayfastNotifyRoute: ApiPayfastNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
